# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LCCWiFiApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LCCWiFiApp
  pod 'Google/SignIn'
  pod 'Firebase/Core'

  target 'LCCWiFiAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LCCWiFiApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LCCWiFiApp-tvOS

  target 'LCCWiFiApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
